server:
  port: 7001

logbook:
  exclude:
    - /health
    - /admin/**
  filter.enabled: true
  format.style: curl
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  write:
    category: http.wire-log
    level: INFO
#   chunk-size: 1000